/* ============================================================
   universidades-brasil.js
   Lista curada de instituições de ensino superior do Brasil
   (universidades federais, institutos federais, universidades
   estaduais e as principais universidades/faculdades privadas
   por número de alunos).

   IMPORTANTE: esta NÃO é a base completa do e-MEC (que tem
   ~2.600 instituições e não está acessível para scraping
   automatizado no momento). Cobre as instituições onde a
   grande maioria dos estudantes brasileiros está matriculada.
   O campo continua editável em texto livre — se a instituição
   do usuário não estiver na lista, ele digita normalmente.

   Cada entrada: [nome completo, sigla, UF]
   ============================================================ */
(function (global) {
  'use strict';

  const INSTITUICOES = [
  ['Centro Universitário 7 de Setembro','UNI7','CE'],
  ['Centro Universitário Adventista de São Paulo','UNASP','SP'],
  ['Centro Universitário AGES','UNIAGES','BA'],
  ['Centro Universitário Alves Faria','UNIALFA','GO'],
  ['Centro Universitário Anhanguera de Campo Grande','UNIDERP','MS'],
  ['Centro Universitário Anhembi Morumbi','UAM','SP'],
  ['Centro Universitário Aparício Carvalho','FIMCA','RO'],
  ['Centro Universitário Araguaia','UNIARA','GO'],
  ['Centro Universitário Assis Gurgacz','FAG','PR'],
  ['Centro Universitário Assunção','UNIFAI','SP'],
  ['Centro Universitário Augusto Motta','UNISUAM','RJ'],
  ['Centro Universitário Autônomo do Brasil','UNIBRASIL','PR'],
  ['Centro Universitário Avantis','UNIAVAN','SC'],
  ['Centro Universitário Barão de Mauá','CBM','SP'],
  ['Centro Universitário Barriga Verde','UNIBAVE','SC'],
  ['Centro Universitário Belas Artes','Belas Artes','SP'],
  ['Centro Universitário Campos de Andrade','UNIANDRADE','PR'],
  ['Centro Universitário Cândido Rondon','UNIRONDON','MT'],
  ['Centro Universitário Celso Lisboa','UCL','RJ'],
  ['Centro Universitário Cenecista de Osório','UNICNEC','RS'],
  ['Centro Universitário Central Paulista','UNICEP','SP'],
  ['Centro Universitário CESMAC','CESMAC','AL'],
  ['Centro Universitário Cesumar','UniCesumar','PR'],
  ['Centro Universitário Ceuma','UniCEUMA','MA'],
  ['Centro Universitário Christus','UNICHRISTUS','CE'],
  ['Centro Universitário Curitiba','UNICURITIBA','PR'],
  ['Centro Universitário de Anápolis','UniEVANGÉLICA','GO'],
  ['Centro Universitário de Araraquara','UNIARA','SP'],
  ['Centro Universitário de Belo Horizonte','UNI-BH','MG'],
  ['Centro Universitário de Brasília','CEUB','DF'],
  ['Centro Universitário de Formiga','UNIFOR-MG','MG'],
  ['Centro Universitário de Goiás','UNI-ANHANGUERA','GO'],
  ['Centro Universitário de João Pessoa','UNIPÊ','PB'],
  ['Centro Universitário de Lavras','UNILAVRAS','MG'],
  ['Centro Universitário de Maringá','UniCesumar','PR'],
  ['Centro Universitário de Mato Grosso do Sul','UNIGRAN','MS'],
  ['Centro Universitário de Patos de Minas','UNIPAM','MG'],
  ['Centro Universitário de Várzea Grande','UNIVAG','MT'],
  ['Centro Universitário Dinâmica das Cataratas','UDC','PR'],
  ['Centro Universitário do Estado do Pará','CESUPA','PA'],
  ['Centro Universitário do Leste de Minas Gerais','UNILESTE','MG'],
  ['Centro Universitário do Norte','UNINORTE','AM'],
  ['Centro Universitário do Vale do Ipojuca','UNIFAVIP','PE'],
  ['Centro Universitário Dom Bosco','UNDB','MA'],
  ['Centro Universitário Doutor Leão Sampaio','UNILEÃO','CE'],
  ['Centro Universitário Estácio da Bahia','ESTÁCIO-BA','BA'],
  ['Centro Universitário Estácio de Santa Catarina','ESTÁCIO-SC','SC'],
  ['Centro Universitário Estácio do Ceará','ESTÁCIO FIC','CE'],
  ['Centro Universitário Facex','UNIFACEX','RN'],
  ['Centro Universitário Facipe','FACIPE','PE'],
  ['Centro Universitário FADERGS','FADERGS','RS'],
  ['Centro Universitário Fametro','UNIFAMETRO','CE'],
  ['Centro Universitário FAMETRO Manaus','FAMETRO-AM','AM'],
  ['Centro Universitário Farias Brito','FFB','CE'],
  ['Centro Universitário FEI','FEI','SP'],
  ['Centro Universitário FIBRA','FIBRA','PA'],
  ['Centro Universitário Filadélfia','UniFil','PR'],
  ['Centro Universitário FMU','FMU','SP'],
  ['Centro Universitário Franciscano','UNIFRA','RS'],
  ['Centro Universitário FTC','UNIFTC','BA'],
  ['Centro Universitário Fundação Santo André','FSA','SP'],
  ['Centro Universitário Geraldo Di Biase','UGB','RJ'],
  ['Centro Universitário Governador Ozanam Coelho','UNIFAGOC','MG'],
  ['Centro Universitário IBMEC','IBMEC','RJ'],
  ['Centro Universitário Ingá','Uningá','PR'],
  ['Centro Universitário INTA','UNINTA','CE'],
  ['Centro Universitário Integrado','Integrado','PR'],
  ['Centro Universitário Internacional Uninter','UNINTER','PR'],
  ['Centro Universitário Izabela Hendrix','Izabela Hendrix','MG'],
  ['Centro Universitário Jorge Amado','UNIJORGE','BA'],
  ['Centro Universitário Jorge Amado (Salvador)','UNIJORGE','BA'],
  ['Centro Universitário La Salle','Unilasalle','RS'],
  ['Centro Universitário La Salle do Rio de Janeiro','UniLaSalle-RJ','RJ'],
  ['Centro Universitário Leonardo da Vinci','UNIASSELVI','SC'],
  ['Centro Universitário Luterano de Manaus','CEULM/ULBRA','AM'],
  ['Centro Universitário Maurício de Nassau (Fortaleza)','UNINASSAU-CE','CE'],
  ['Centro Universitário Metodista Bennett','Bennett','RJ'],
  ['Centro Universitário Metodista IPA','IPA','RS'],
  ['Centro Universitário Metodista Izabela Hendrix','Izabela Hendrix','MG'],
  ['Centro Universitário Metropolitano da Amazônia','UNIFAMAZ','PA'],
  ['Centro Universitário Metropolitano de Maringá','UNIFAMMA','PR'],
  ['Centro Universitário Módulo','MÓDULO','RJ'],
  ['Centro Universitário Moura Lacerda','UNIMOURA','SP'],
  ['Centro Universitário Municipal de São José','USJ','SC'],
  ['Centro Universitário Newton Paiva','Newton Paiva','MG'],
  ['Centro Universitário Nilton Lins','Nilton Lins','AM'],
  ['Centro Universitário Nobre','UNIFAN','BA'],
  ['Centro Universitário Padre Anchieta','UniAnchieta','SP'],
  ['Centro Universitário para o Desenvolvimento do Alto Vale do Itajaí','UNIDAVI','SC'],
  ['Centro Universitário Redentor','UniRedentor','RJ'],
  ['Centro Universitário Ritter dos Reis','UniRitter','RS'],
  ['Centro Universitário Salesiano de São Paulo','UNISAL','SP'],
  ['Centro Universitário Sant\'Anna','UniSant\'Anna','SP'],
  ['Centro Universitário Santo Agostinho','UNIFSA','PI'],
  ['Centro Universitário São Camilo','SÃO CAMILO-BA','BA'],
  ['Centro Universitário São Camilo (SP campus Ipiranga)','SÃO CAMILO-IPI','SP'],
  ['Centro Universitário São Camilo (SP)','SÃO CAMILO','SP'],
  ['Centro Universitário São Lucas','SÃO LUCAS','RO'],
  ['Centro Universitário SATC','SATC','SC'],
  ['Centro Universitário Senac','Senac','SP'],
  ['Centro Universitário SENAC Santo Amaro','SENAC-SP','SP'],
  ['Centro Universitário Serra dos Órgãos','UNIFESO','RJ'],
  ['Centro Universitário Tabosa de Almeida','ASCES-UNITA','PE'],
  ['Centro Universitário Tiradentes','UNIT','AL'],
  ['Centro Universitário Tiradentes (Maceió)','UNIT-AL','AL'],
  ['Centro Universitário Toledo','UNITOLEDO','SP'],
  ['Centro Universitário UNA','UNA','MG'],
  ['Centro Universitário Uniamérica','UNIAMÉRICA','PR'],
  ['Centro Universitário UniDomBosco','UniDomBosco','RS'],
  ['Centro Universitário Unifacs','UNIFACS','BA'],
  ['Centro Universitário Uninovafapi','UNINOVAFAPI','PI'],
  ['Centro Universitário Univates','UNIVATES','RS'],
  ['Centro Universitário Universus Veritas','UNIVERITAS','RJ'],
  ['Centro Universitário Volta Redonda','UniFOA','RJ'],
  ['Escola Bahiana de Medicina e Saúde Pública','Bahiana','BA'],
  ['Escola Superior de Educação Física de Goiás','ESEFEGO','GO'],
  ['Escola Superior de Guerra','ESG','RJ'],
  ['Escola Superior de Propaganda e Marketing','ESPM','SP'],
  ['Faculdade Adventista da Bahia','FADBA','BA'],
  ['Faculdade Ages','AGES','BA'],
  ['Faculdade Anhanguera','Anhanguera','SP'],
  ['Faculdade Anhanguera de Anápolis','Anhanguera-GO','GO'],
  ['Faculdade Anísio Teixeira','FAT','BA'],
  ['Faculdade Araguaia','FARA','GO'],
  ['Faculdade Ateneu','FATE','CE'],
  ['Faculdade Ávila','FAAVILA','GO'],
  ['Faculdade Baiana de Ciências Contábeis e Administrativas','FABAC','BA'],
  ['Faculdade Baiana de Direito','','BA'],
  ['Faculdade Boa Viagem (Devry)','FBV','PE'],
  ['Faculdade Cambury','Cambury','GO'],
  ['Faculdade Cathedral','Cathedral','RR'],
  ['Faculdade CDL','FCDL','CE'],
  ['Faculdade CERS','CERS','SP'],
  ['Faculdade Cesusc','CESUSC','SC'],
  ['Faculdade Ciências da Vida','FCV','MG'],
  ['Faculdade Cosmopolita','FAC','AP'],
  ['Faculdade Cruzeiro do Sul','Cruzeiro do Sul','SP'],
  ['Faculdade Cruzeiro do Sul Virtual','CRUZEIRO DO SUL VIRTUAL','SP'],
  ['Faculdade da Cidade do Salvador','FCS','BA'],
  ['Faculdade Damas da Instrução Cristã','FADIC','PE'],
  ['Faculdade Damásio','Damásio','SP'],
  ['Faculdade das Américas','FAM','SP'],
  ['Faculdade de Ciências Biomédicas de Cacoal','FACIMED','RO'],
  ['Faculdade de Ciências Médicas da Paraíba','FCM-PB','PB'],
  ['Faculdade de Ciências Médicas de Minas Gerais','FCMMG','MG'],
  ['Faculdade de Ciências Médicas de São José dos Campos','Humanitas','SP'],
  ['Faculdade de Ciências Médicas de Uberlândia','FCMU','MG'],
  ['Faculdade de Ciências Sociais Aplicadas de Cacoal','FACIMED','RO'],
  ['Faculdade de Ciências Sociais e Aplicadas','SÓ FACSA','PB'],
  ['Faculdade de Direito de Anápolis','FADA','GO'],
  ['Faculdade de Direito Milton Campos','FDMC','MG'],
  ['Faculdade de Enfermagem Nova Esperança','FACENE','PB'],
  ['Faculdade de Fortaleza','FAFOR','CE'],
  ['Faculdade de Medicina de Barbacena','FAME','MG'],
  ['Faculdade de Medicina de Marília','FAMEMA','SP'],
  ['Faculdade de Medicina de São José do Rio Preto','FAMERP','SP'],
  ['Faculdade de Medicina do ABC','FMABC','SP'],
  ['Faculdade de Rondônia','FARO','RO'],
  ['Faculdade de Tecnologia (Fatec)','FATEC','SP'],
  ['Faculdade de Tecnologia e Ciências','FTC','BA'],
  ['Faculdade de Tecnologia Empresarial','FATENE','BA'],
  ['Faculdade Delta','Delta','GO'],
  ['Faculdade Descomplica','Descomplica','RJ'],
  ['Faculdade Descomplica (Cogna)','Descomplica','RJ'],
  ['Faculdade Descomplica Medicina','','RJ'],
  ['Faculdade Doctum','Doctum','MG'],
  ['Faculdade dos Guararapes','FG','PE'],
  ['Faculdade Estácio BH','ESTÁCIO-BH','MG'],
  ['Faculdade Estácio de Goiás','ESTÁCIO-GO','GO'],
  ['Faculdade Estácio de Roraima','ESTÁCIO-RR','RR'],
  ['Faculdade Estácio de Sá de Juiz de Fora','ESTÁCIO-JF','MG'],
  ['Faculdade Estácio do Amapá','ESTÁCIO-AP','AP'],
  ['Faculdade Estácio Fal','FAL','AL'],
  ['Faculdade Frassinetti do Recife','FAFIRE','PE'],
  ['Faculdade Governador Ozanam Coelho','FAGOC','MG'],
  ['Faculdade Grande Fortaleza','FGF','CE'],
  ['Faculdade Guanambi','FG','BA'],
  ['Faculdade IBMEC','IBMEC','RJ'],
  ['Faculdade Independente do Nordeste','FAINOR','BA'],
  ['Faculdade Integrada Tiradentes','FITS','AL'],
  ['Faculdade Interamericana de Porto Velho','UNIRON','RO'],
  ['Faculdade Internacional da Paraíba','FPB','PB'],
  ['Faculdade Joaquim Nabuco','FJN','PE'],
  ['Faculdade Kroton','Kroton','MG'],
  ['Faculdade Luciano Feijão','FLF','CE'],
  ['Faculdade Machado Sobrinho','FAMASUL','MG'],
  ['Faculdade Maria Milza','FAMAM','BA'],
  ['Faculdade Martha Falcão','UNIFAMAZ-AM','AM'],
  ['Faculdade Maurício de Nassau','UNINASSAU','PE'],
  ['Faculdade Mauricio de Nassau (João Pessoa)','UNINASSAU-PB','PB'],
  ['Faculdade Metodista Granbery','FMG','MG'],
  ['Faculdade Metropolitana da Grande Recife','FMGR','PE'],
  ['Faculdade Metropolitana de Manaus','FAMETRO','AM'],
  ['Faculdade Nobre de Feira de Santana','FAN','BA'],
  ['Faculdade Nordeste','FANOR','CE'],
  ['Faculdade Objetivo','Objetivo','GO'],
  ['Faculdade Paraíso do Ceará','FAP','CE'],
  ['Faculdade Pernambucana de Saúde','FPS','PE'],
  ['Faculdade Pitágoras','Pitágoras','MG'],
  ['Faculdade Pitágoras (Cogna)','Pitágoras','MG'],
  ['Faculdade Pitágoras de Betim','Pitágoras-Betim','MG'],
  ['Faculdade Presidente Antônio Carlos','UNIPAC','MG'],
  ['Faculdade Raimundo Marinho','FRM','AL'],
  ['Faculdade Regional da Bahia','UNIRB','BA'],
  ['Faculdade Regional de Direito','FRD','BA'],
  ['Faculdade Regional de Filosofia, Ciências e Letras de Candeias','FARCC','BA'],
  ['Faculdade Ruy Barbosa','UNIRUY','BA'],
  ['Faculdade Santa Emília','FASE','PB'],
  ['Faculdade Santa Marcelina','FASM','SP'],
  ['Faculdade Santíssimo Sacramento','FSSSA','BA'],
  ['Faculdade São Francisco de Barreiras','FASB','BA'],
  ['Faculdade São Lucas (Porto Velho)','SÃO LUCAS-RO','RO'],
  ['Faculdade SEAMA','SEAMA','AP'],
  ['Faculdade Ser Educacional','Ser Educacional','PE'],
  ['Faculdade Sete de Setembro','FASETE','BA'],
  ['Faculdade Sete Lagoas','FACSETE','MG'],
  ['Faculdade Social da Bahia','FSBA','BA'],
  ['Faculdade Terra Nordeste','FATENE-CE','CE'],
  ['Faculdade União de Goyazes','UNIFUCAMP','GO'],
  ['Faculdade Uniateneu','UNIATENEU','CE'],
  ['Faculdade UNIFAVIP Wyden','UNIFAVIP','PE'],
  ['Faculdade UNIP Interativa','UNIP EAD','SP'],
  ['Faculdade Unopar','UNOPAR','PR'],
  ['Faculdade Wyden','Wyden','PE'],
  ['Faculdade YDUQS','YDUQS','RJ'],
  ['Faculdade Zacarias de Góes','FAZAG','BA'],
  ['Faculdades Integradas do Brasil','UniBrasil','PR'],
  ['Faculdades Metropolitanas Unidas','FMU','SP'],
  ['Faculdades Oswaldo Cruz','FOC','SP'],
  ['Fundação Getulio Vargas','FGV','SP'],
  ['Fundação Universidade Federal de Ciências da Saúde de Porto Alegre','UFCSPA','RS'],
  ['Instituto de Ensino e Pesquisa','INSPER','SP'],
  ['Instituto de Ensino Superior do Amapá','IESAP','AP'],
  ['Instituto de Ensino Superior Presidente Antônio Carlos','IESP','BA'],
  ['Instituto de Ensino Superior Presidente Kennedy','IESPK','AM'],
  ['Instituto Federal Baiano','IF Baiano','BA'],
  ['Instituto Federal Catarinense','IFC','SC'],
  ['Instituto Federal da Bahia','IFBA','BA'],
  ['Instituto Federal da Paraíba','IFPB','PB'],
  ['Instituto Federal de Alagoas','IFAL','AL'],
  ['Instituto Federal de Brasília','IFB','DF'],
  ['Instituto Federal de Educação, Ciência e Tecnologia de Brasília','IFB','DF'],
  ['Instituto Federal de Goiás','IFG','GO'],
  ['Instituto Federal de Mato Grosso','IFMT','MT'],
  ['Instituto Federal de Mato Grosso do Sul','IFMS','MS'],
  ['Instituto Federal de Minas Gerais','IFMG','MG'],
  ['Instituto Federal de Pernambuco','IFPE','PE'],
  ['Instituto Federal de Rondônia','IFRO','RO'],
  ['Instituto Federal de Roraima','IFRR','RR'],
  ['Instituto Federal de Santa Catarina','IFSC','SC'],
  ['Instituto Federal de São Paulo','IFSP','SP'],
  ['Instituto Federal de Sergipe','IFS','SE'],
  ['Instituto Federal do Acre','IFAC','AC'],
  ['Instituto Federal do Amapá','IFAP','AP'],
  ['Instituto Federal do Amazonas','IFAM','AM'],
  ['Instituto Federal do Ceará','IFCE','CE'],
  ['Instituto Federal do Espírito Santo','IFES','ES'],
  ['Instituto Federal do Maranhão','IFMA','MA'],
  ['Instituto Federal do Norte de Minas Gerais','IFNMG','MG'],
  ['Instituto Federal do Pará','IFPA','PA'],
  ['Instituto Federal do Paraná','IFPR','PR'],
  ['Instituto Federal do Piauí','IFPI','PI'],
  ['Instituto Federal do Rio de Janeiro','IFRJ','RJ'],
  ['Instituto Federal do Rio Grande do Norte','IFRN','RN'],
  ['Instituto Federal do Rio Grande do Sul','IFRS','RS'],
  ['Instituto Federal do Sertão Pernambucano','IF Sertão-PE','PE'],
  ['Instituto Federal do Sudeste de Minas Gerais','IF Sudeste MG','MG'],
  ['Instituto Federal do Sul de Minas Gerais','IFSULDEMINAS','MG'],
  ['Instituto Federal do Tocantins','IFTO','TO'],
  ['Instituto Federal do Triângulo Mineiro','IFTM','MG'],
  ['Instituto Federal Farroupilha','IFFar','RS'],
  ['Instituto Federal Fluminense','IFF','RJ'],
  ['Instituto Federal Goiano','IF Goiano','GO'],
  ['Instituto Federal Sul-rio-grandense','IFSul','RS'],
  ['Instituto Mauá de Tecnologia','IMT','SP'],
  ['Instituto Militar de Engenharia','IME','RJ'],
  ['Instituto Tecnológico de Aeronáutica','ITA','SP'],
  ['Newton Paiva Faculdades','Newton Paiva','MG'],
  ['Pontifícia Universidade Católica de Campinas','PUC-Campinas','SP'],
  ['Pontifícia Universidade Católica de Goiás','PUC Goiás','GO'],
  ['Pontifícia Universidade Católica de Minas Gerais','PUC Minas','MG'],
  ['Pontifícia Universidade Católica de São Paulo','PUC-SP','SP'],
  ['Pontifícia Universidade Católica do Paraná','PUCPR','PR'],
  ['Pontifícia Universidade Católica do Rio de Janeiro','PUC-Rio','RJ'],
  ['Pontifícia Universidade Católica do Rio Grande do Sul','PUCRS','RS'],
  ['Universidade Anhanguera','Anhanguera','SP'],
  ['Universidade Anhanguera - Leme','UNIAN','SP'],
  ['Universidade Anhanguera - Uniderp','UNIDERP','MS'],
  ['Universidade Anhembi Morumbi','UAM','SP'],
  ['Universidade Bandeirante Anhanguera','UNIBAN','SP'],
  ['Universidade Bandeirante de São Paulo','UNIBAN','SP'],
  ['Universidade Braz Cubas','UBC','SP'],
  ['Universidade Camilo Castelo Branco','UNICASTELO','SP'],
  ['Universidade Cândido Mendes','UCAM','RJ'],
  ['Universidade Católica de Brasília','UCB','DF'],
  ['Universidade Católica de Goiás (PUC Goiás)','PUC Goiás','GO'],
  ['Universidade Católica de Pelotas','UCPel','RS'],
  ['Universidade Católica de Pernambuco','UNICAP','PE'],
  ['Universidade Católica do Salvador','UCSAL','BA'],
  ['Universidade Cesumar','UNICESUMAR','PR'],
  ['Universidade Ceuma','CEUMA','MA'],
  ['Universidade Comunitária da Região de Chapecó','UNOCHAPECÓ','SC'],
  ['Universidade Cruzeiro do Sul','UNICSUL','SP'],
  ['Universidade da Integração Internacional da Lusofonia Afro-Brasileira','UNILAB','CE'],
  ['Universidade da Região de Joinville','UNIVILLE','SC'],
  ['Universidade de Brasília','UnB','DF'],
  ['Universidade de Caxias do Sul','UCS','RS'],
  ['Universidade de Cuiabá','UNIC','MT'],
  ['Universidade de Fortaleza','UNIFOR','CE'],
  ['Universidade de Passo Fundo','UPF','RS'],
  ['Universidade de Pernambuco (privadas assoc.)','','PE'],
  ['Universidade de Ribeirão Preto','UNAERP','SP'],
  ['Universidade de Santa Cruz do Sul','UNISC','RS'],
  ['Universidade de Santo Amaro','UNISA','SP'],
  ['Universidade de São Paulo','USP','SP'],
  ['Universidade de Sorocaba','UNISO','SP'],
  ['Universidade de Taubaté','UNITAU','SP'],
  ['Universidade do Estado da Bahia','UNEB','BA'],
  ['Universidade do Estado de Mato Grosso','UNEMAT','MT'],
  ['Universidade do Estado de Minas Gerais','UEMG','MG'],
  ['Universidade do Estado de Santa Catarina','UDESC','SC'],
  ['Universidade do Estado do Amazonas','UEA','AM'],
  ['Universidade do Estado do Pará','UEPA','PA'],
  ['Universidade do Estado do Rio de Janeiro','UERJ','RJ'],
  ['Universidade do Estado do Rio Grande do Norte','UERN','RN'],
  ['Universidade do Extremo Sul Catarinense','UNESC','SC'],
  ['Universidade do Oeste de Santa Catarina','UNOESC','SC'],
  ['Universidade do Sul de Santa Catarina','UNISUL','SC'],
  ['Universidade do Vale do Itajaí','UNIVALI','SC'],
  ['Universidade do Vale do Paraíba','UNIVAP','SP'],
  ['Universidade do Vale do Rio dos Sinos','UNISINOS','RS'],
  ['Universidade Estácio de Sá','Estácio','RJ'],
  ['Universidade Estadual da Bahia','UNEB','BA'],
  ['Universidade Estadual da Paraíba','UEPB','PB'],
  ['Universidade Estadual de Campinas','UNICAMP','SP'],
  ['Universidade Estadual de Ciências da Saúde de Alagoas','UNCISAL','AL'],
  ['Universidade Estadual de Feira de Santana','UEFS','BA'],
  ['Universidade Estadual de Goiás','UEG','GO'],
  ['Universidade Estadual de Goiás (Anápolis)','UEG','GO'],
  ['Universidade Estadual de Londrina','UEL','PR'],
  ['Universidade Estadual de Maringá','UEM','PR'],
  ['Universidade Estadual de Maringá (privadas assoc.)','','PR'],
  ['Universidade Estadual de Mato Grosso do Sul','UEMS','MS'],
  ['Universidade Estadual de Montes Claros','UNIMONTES','MG'],
  ['Universidade Estadual de Pernambuco','UPE','PE'],
  ['Universidade Estadual de Ponta Grossa','UEPG','PR'],
  ['Universidade Estadual de Roraima','UERR','RR'],
  ['Universidade Estadual de Santa Cruz','UESC','BA'],
  ['Universidade Estadual do Amazonas','UEA','AM'],
  ['Universidade Estadual do Ceará','UECE','CE'],
  ['Universidade Estadual do Centro-Oeste','UNICENTRO','PR'],
  ['Universidade Estadual do Maranhão','UEMA','MA'],
  ['Universidade Estadual do Norte do Paraná','UENP','PR'],
  ['Universidade Estadual do Norte Fluminense','UENF','RJ'],
  ['Universidade Estadual do Oeste do Paraná','UNIOESTE','PR'],
  ['Universidade Estadual do Piauí','UESPI','PI'],
  ['Universidade Estadual do Rio Grande do Sul','UERGS','RS'],
  ['Universidade Estadual do Sudoeste da Bahia','UESB','BA'],
  ['Universidade Estadual Paulista Júlio de Mesquita Filho','UNESP','SP'],
  ['Universidade Estadual Vale do Acaraú','UVA','CE'],
  ['Universidade Evangélica de Goiás','UniEVANGÉLICA','GO'],
  ['Universidade Federal da Bahia','UFBA','BA'],
  ['Universidade Federal da Fronteira Sul','UFFS','RS'],
  ['Universidade Federal da Integração Latino-Americana','UNILA','PR'],
  ['Universidade Federal da Paraíba','UFPB','PB'],
  ['Universidade Federal de Alagoas','UFAL','AL'],
  ['Universidade Federal de Alfenas','UNIFAL-MG','MG'],
  ['Universidade Federal de Campina Grande','UFCG','PB'],
  ['Universidade Federal de Catalão','UFCAT','GO'],
  ['Universidade Federal de Ciências da Saúde de Porto Alegre','UFCSPA','RS'],
  ['Universidade Federal de Goiás','UFG','GO'],
  ['Universidade Federal de Goiás (privadas assoc.)','','GO'],
  ['Universidade Federal de Itajubá','UNIFEI','MG'],
  ['Universidade Federal de Jataí','UFJ','GO'],
  ['Universidade Federal de Jataí (antigo campus UFG)','UFJ','GO'],
  ['Universidade Federal de Juiz de Fora','UFJF','MG'],
  ['Universidade Federal de Lavras','UFLA','MG'],
  ['Universidade Federal de Mato Grosso','UFMT','MT'],
  ['Universidade Federal de Mato Grosso do Sul','UFMS','MS'],
  ['Universidade Federal de Minas Gerais','UFMG','MG'],
  ['Universidade Federal de Ouro Preto','UFOP','MG'],
  ['Universidade Federal de Pelotas','UFPel','RS'],
  ['Universidade Federal de Pernambuco','UFPE','PE'],
  ['Universidade Federal de Rondônia','UNIR','RO'],
  ['Universidade Federal de Rondonópolis','UFR','MT'],
  ['Universidade Federal de Roraima','UFRR','RR'],
  ['Universidade Federal de Santa Catarina','UFSC','SC'],
  ['Universidade Federal de Santa Maria','UFSM','RS'],
  ['Universidade Federal de São Carlos','UFSCar','SP'],
  ['Universidade Federal de São João del-Rei','UFSJ','MG'],
  ['Universidade Federal de São Paulo','UNIFESP','SP'],
  ['Universidade Federal de São Paulo (Escola Paulista de Medicina)','UNIFESP-EPM','SP'],
  ['Universidade Federal de Sergipe','UFS','SE'],
  ['Universidade Federal de Uberlândia','UFU','MG'],
  ['Universidade Federal de Viçosa','UFV','MG'],
  ['Universidade Federal do ABC','UFABC','SP'],
  ['Universidade Federal do Acre','UFAC','AC'],
  ['Universidade Federal do Amapá','UNIFAP','AP'],
  ['Universidade Federal do Amazonas','UFAM','AM'],
  ['Universidade Federal do Cariri','UFCA','CE'],
  ['Universidade Federal do Ceará','UFC','CE'],
  ['Universidade Federal do Espírito Santo','UFES','ES'],
  ['Universidade Federal do Estado do Rio de Janeiro','UNIRIO','RJ'],
  ['Universidade Federal do Maranhão','UFMA','MA'],
  ['Universidade Federal do Oeste da Bahia','UFOB','BA'],
  ['Universidade Federal do Oeste do Pará','UFOPA','PA'],
  ['Universidade Federal do Pampa','UNIPAMPA','RS'],
  ['Universidade Federal do Pará','UFPA','PA'],
  ['Universidade Federal do Paraná','UFPR','PR'],
  ['Universidade Federal do Piauí','UFPI','PI'],
  ['Universidade Federal do Recôncavo da Bahia','UFRB','BA'],
  ['Universidade Federal do Rio de Janeiro','UFRJ','RJ'],
  ['Universidade Federal do Rio Grande','FURG','RS'],
  ['Universidade Federal do Rio Grande do Norte','UFRN','RN'],
  ['Universidade Federal do Rio Grande do Sul','UFRGS','RS'],
  ['Universidade Federal do Sul da Bahia','UFSB','BA'],
  ['Universidade Federal do Sul e Sudeste do Maranhão','UFSSMA','MA'],
  ['Universidade Federal do Sul e Sudeste do Pará','UNIFESSPA','PA'],
  ['Universidade Federal do Tocantins','UFT','TO'],
  ['Universidade Federal do Triângulo Mineiro','UFTM','MG'],
  ['Universidade Federal do Vale do São Francisco','UNIVASF','PE'],
  ['Universidade Federal dos Vales do Jequitinhonha e Mucuri','UFVJM','MG'],
  ['Universidade Federal Fluminense','UFF','RJ'],
  ['Universidade Federal Fluminense (privadas conveniadas)','','RJ'],
  ['Universidade Federal Latino-Americana','UNILA','PR'],
  ['Universidade Federal Rural de Pernambuco','UFRPE','PE'],
  ['Universidade Federal Rural do Rio de Janeiro','UFRRJ','RJ'],
  ['Universidade Federal Rural do Semi-Árido','UFERSA','RN'],
  ['Universidade Feevale','FEEVALE','RS'],
  ['Universidade FUMEC','FUMEC','MG'],
  ['Universidade Gama Filho','UGF','RJ'],
  ['Universidade Guarulhos','UNG','SP'],
  ['Universidade Ibirapuera','UNIB','SP'],
  ['Universidade Iguaçu','UNIG','RJ'],
  ['Universidade José do Rosário Vellano','UNIFENAS','MG'],
  ['Universidade Luterana do Brasil','ULBRA','RS'],
  ['Universidade Maurício de Nassau','UNINASSAU','PE'],
  ['Universidade Metodista de Piracicaba','UNIMEP','SP'],
  ['Universidade Metodista de São Paulo','UMESP','SP'],
  ['Universidade Metropolitana de Santos','UNIMES','SP'],
  ['Universidade Norte do Paraná','UNOPAR','PR'],
  ['Universidade Nove de Julho','UNINOVE','SP'],
  ['Universidade Paulista','UNIP','SP'],
  ['Universidade Positivo','UP','PR'],
  ['Universidade Potiguar','UnP','RN'],
  ['Universidade Presbiteriana Mackenzie','Mackenzie','SP'],
  ['Universidade Regional de Blumenau','FURB','SC'],
  ['Universidade Regional do Noroeste do Estado do RS','UNIJUÍ','RS'],
  ['Universidade Regional Integrada do Alto Uruguai e das Missões','URI','RS'],
  ['Universidade Salgado de Oliveira','UNIVERSO','RJ'],
  ['Universidade Salvador','UNIFACS','BA'],
  ['Universidade São Francisco','USF','SP'],
  ['Universidade São Judas Tadeu','USJT','SP'],
  ['Universidade São Marcos','USM','SP'],
  ['Universidade Tecnológica Federal do Paraná','UTFPR','PR'],
  ['Universidade Tiradentes','UNIT','SE'],
  ['Universidade Tuiuti do Paraná','UTP','PR'],
  ['Universidade Uninter','UNINTER','PR'],
  ['Universidade Unopar Anhanguera','UNOPAR','PR'],
  ['Universidade Vale do Rio Doce','UNIVALE','MG'],
  ['Universidade Vale do Rio Verde','UninCor','MG'],
  ['Universidade Veiga de Almeida','UVA-RJ','RJ'],
  ];

  function normalizar(str) {
    return (str || '')
      .toString()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
      .trim();
  }

  /**
   * Busca instituições por termo (nome ou sigla), ignorando acentos/caixa.
   * @param {string} termo
   * @param {number} limite
   * @returns {Array<{nome:string, sigla:string, uf:string}>}
   */
  function buscarInstituicoes(termo, limite = 8) {
    const t = normalizar(termo);
    if (!t || t.length < 2) return [];

    const palavras = t.split(/\s+/).filter(Boolean);

    const resultados = [];
    for (let i = 0; i < INSTITUICOES.length; i++) {
      const [nome, sigla, uf] = INSTITUICOES[i];
      const nomeNorm = normalizar(nome);
      const siglaNorm = normalizar(sigla);

      let score = -1;
      if (siglaNorm === t) score = 0;
      else if (siglaNorm.startsWith(t)) score = 1;
      else if (nomeNorm.startsWith(t)) score = 2;
      else if (nomeNorm.includes(' ' + t)) score = 3;
      else if (nomeNorm.includes(t) || siglaNorm.includes(t)) score = 4;
      else if (palavras.length > 1 && palavras.every(p => nomeNorm.includes(p))) score = 5;

      if (score >= 0) resultados.push({ nome, sigla, uf, score });
    }

    resultados.sort((a, b) => a.score - b.score || a.nome.localeCompare(b.nome, 'pt-BR'));
    return resultados.slice(0, limite);
  }

  global.SLC_Universidades = { buscarInstituicoes, INSTITUICOES };
})(typeof window !== 'undefined' ? window : this);
